name: Python Testing Pipeline

# 1. Trigger the workflow on every git push to any branch
on: [push]

jobs:
  run-pytest:
    # 2. Tell GitHub to spin up a fresh Ubuntu Linux virtual machine
    runs-on: ubuntu-latest

    # 3. set up the python versions to be used
    strategy:
      matrix:
    
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    # 4. Download (checkout) repository code onto the virtual machine
    - name: Check out repository code
      uses: actions/checkout@v4

    # 5. Install Python 3 and higher on the virtual machine
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    # 6. cache libraries to not have to install them every time the workflow runs
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      
    

    # 7. Install imported libraries (SymPy, NumPy, Matplotlib, Pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov numpy sympy matplotlib 

    # 8. Run tests
    - name: Run Pytest
      run: |
        pytest --cov=calculator --cov-fail-under=80 --cov-report=html -v
    
    # 9. Upload HTML coverage report as an artifact
    - name: Upload HTML Coverage Report Artifact
      uses: actions/upload-artifact@v4
      if: always()  # <-- This forces the upload even if the previous test step fails!
      with:
        name: python-coverage-report-${{ matrix.python-version }}
        path: htmlcov/


