name: Python Testing Pipeline

# 1. Trigger the workflow on every git push to any branch
on: [push]

jobs:
  run-pytest:
    # 2. Tell GitHub to spin up a fresh Ubuntu Linux virtual machine
    runs-on: ubuntu-latest

    # 3. set up the python versions to be used
    strategy:
      matrix:
    
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    # 4. Download (checkout) repository code onto the virtual machine
    - name: Check out repository code
      uses: actions/checkout@v4

    # 5. Install Python 3 and higher on the virtual machine
    - name: Set up Python
      uses: actions/setup-python@v5
      

    # 6. Install imported libraries (SymPy, NumPy, Matplotlib, Pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov numpy sympy matplotlib 

    # 7. Run tests
    - name: Run Pytest
      run: |
        pytest --cov=calculator --cov-fail-under=80 -v